apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/component: assistente-portaria
  app.kubernetes.io/part-of: condohome
