apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: condohome
resources:
  - deployment.yaml
commonLabels:
  app.kubernetes.io/part-of: condohome-platform
  app.kubernetes.io/component: booking
