apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: condohome

resources:
  - ../../base/shared
  - ../../base/register
  - ../../base/billing
  - ../../base/documents
  - ../../base/booking
  - ../../base/notification
  - ../../base/finance
  - ../../base/ai-assistant
  - ../../base/gateway
  - ../../base/n8n

images:
  - name: ghcr.io/rmaneschy/ms-condohome-register
    newTag: staging
  - name: ghcr.io/rmaneschy/ms-condohome-billing
    newTag: staging
  - name: ghcr.io/rmaneschy/ms-condohome-documents
    newTag: staging
  - name: ghcr.io/rmaneschy/ms-condohome-booking
    newTag: staging
  - name: ghcr.io/rmaneschy/ms-condohome-notification
    newTag: staging
  - name: ghcr.io/rmaneschy/ms-condohome-finance
    newTag: staging
  - name: ghcr.io/rmaneschy/ms-condohome-ai-assistant
    newTag: staging
  - name: ghcr.io/rmaneschy/ms-condohome-gateway
    newTag: staging

commonLabels:
  environment: staging
