apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: condohome

resources:
  - ../../base/shared
  - ../../base/register
  - ../../base/billing
  - ../../base/documents
  - ../../base/booking
  - ../../base/notification
  - ../../base/finance
  - ../../base/ai-assistant
  - ../../base/gateway
  - ../../base/portal-web
  - ../../base/assistente-portaria
  - ../../base/n8n

replicas:
  - name: gateway
    count: 2
  - name: register
    count: 2
  - name: portal-web
    count: 2
  - name: assistente-portaria
    count: 2

images:
  - name: ghcr.io/rmaneschy/ms-condohome-register
    newTag: latest
  - name: ghcr.io/rmaneschy/ms-condohome-billing
    newTag: latest
  - name: ghcr.io/rmaneschy/ms-condohome-documents
    newTag: latest
  - name: ghcr.io/rmaneschy/ms-condohome-booking
    newTag: latest
  - name: ghcr.io/rmaneschy/ms-condohome-notification
    newTag: latest
  - name: ghcr.io/rmaneschy/ms-condohome-finance
    newTag: latest
  - name: ghcr.io/rmaneschy/ms-condohome-ai-assistant
    newTag: latest
  - name: ghcr.io/rmaneschy/ms-condohome-gateway
    newTag: latest
  - name: ghcr.io/rmaneschy/portal-condohome-web
    newTag: latest
  - name: ghcr.io/rmaneschy/assistente-portaria
    newTag: latest

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"

commonLabels:
  environment: production
