apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: condohome

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml

commonLabels:
  app.kubernetes.io/part-of: condohome-platform
