---
apiVersion: v1
kind: Secret
metadata:
  name: condohome-db-secret
  namespace: condohome
type: Opaque
stringData:
  username: condohome
  password: CHANGE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: condohome-api-secrets
  namespace: condohome
type: Opaque
stringData:
  asaas-api-key: CHANGE_ME
  openai-api-key: CHANGE_ME
  mail-username: CHANGE_ME
  mail-password: CHANGE_ME
  evolution-api-key: CHANGE_ME
  n8n-password: CHANGE_ME
